# Generated by Django 5.0.14 on 2026-08-25 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customerprofile_college_id_user_college_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
    ]
