# Generated by Django 5.0.14 on 2026-08-21 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('subject', models.CharField(max_length=200)),
                ('message_template', models.TextField()),
                ('notification_type', models.CharField(choices=[('order_status', 'Order Status'), ('food_ready', 'Food Ready'), ('order_delayed', 'Order Delayed'), ('special_offer', 'Special Offer'), ('coupon_announcement', 'Coupon Announcement'), ('canteen_announcement', 'Canteen Announcement'), ('general', 'General Message'), ('delivery_update', 'Delivery Update')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('order_status', 'Order Status'), ('food_ready', 'Food Ready'), ('order_delayed', 'Order Delayed'), ('special_offer', 'Special Offer'), ('coupon_announcement', 'Coupon Announcement'), ('canteen_announcement', 'Canteen Announcement'), ('general', 'General Message'), ('delivery_update', 'Delivery Update')], default='general', max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('is_sent_to_email', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='notificatio_user_id_427e4b_idx'), models.Index(fields=['created_at'], name='notificatio_created_46ad24_idx'), models.Index(fields=['notification_type'], name='notificatio_notific_f2898f_idx')],
            },
        ),
    ]
